# Generated by Django 5.1.7 on 2025-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
