# Generated by Django 5.1.7 on 2025-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_last_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_logout_device",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
