# Generated by Django 5.1.6 on 2025-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CDSR",
            fields=[
                ("cdsr_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cdsr_no", models.IntegerField(blank=True, null=True)),
                ("cdsr_pg_no", models.IntegerField(blank=True, null=True)),
                ("active_product", models.IntegerField(blank=True, null=True)),
                ("cdsr_name", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_purchase", models.DateField(blank=True, max_length=80)),
                (
                    "product_category",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "product_description",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("product_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "purchase_authority",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "purchase_year",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("remaining_quantity", models.IntegerField()),
                ("single_cost", models.BigIntegerField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=90, null=True)),
                ("total_cost", models.BigIntegerField(blank=True, null=True)),
                (
                    "writeoff_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsumeCDSR",
            fields=[
                (
                    "consume_cdsr_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("consume_cdsr_no", models.IntegerField(blank=True, null=True)),
                ("consume_cdsr_page_no", models.IntegerField(blank=True, null=True)),
                (
                    "consume_cost_per_unit",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "consume_date_of_purchase",
                    models.DateField(blank=True, max_length=255),
                ),
                ("consume_order_no", models.IntegerField(blank=True, null=True)),
                (
                    "consume_cdsr_product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "consume_purchase_quantity",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "consume_purchase_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "consume_supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("consume_total", models.IntegerField(blank=True, null=True)),
                (
                    "final_product_quantity",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "product_grant",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsumeDDSR",
            fields=[
                (
                    "consumeddsr_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "c_purchase_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cdsr_no", models.IntegerField(blank=True, null=True)),
                ("cdsr_pg_no", models.IntegerField(blank=True, null=True)),
                ("consume_cdsr_id", models.BigIntegerField(blank=True, null=True)),
                ("date_of_issue", models.DateField(blank=True, max_length=255)),
                ("ddsr_total", models.FloatField()),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "final_product_quantity1",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("indent_no", models.BigIntegerField(blank=True, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ddsr_purchase_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quantity_issued",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DDSR",
            fields=[
                ("ddsr_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cdsr_name", models.CharField(blank=True, max_length=255, null=True)),
                ("cdsr_no", models.IntegerField(blank=True, null=True)),
                ("cdsr_page_no", models.IntegerField(blank=True, null=True)),
                ("cdsr_table_id", models.BigIntegerField(blank=True, null=True)),
                ("cost_unit", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_receive", models.DateField(blank=True, max_length=255)),
                ("ddsr_no", models.IntegerField(blank=True, null=True)),
                ("ddsr_pg_no", models.IntegerField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("product_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "accepted_product_quantity",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_cost", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "writeoff_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "year_of_buy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WriteOff",
            fields=[
                ("writeoff_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cdsr_no", models.IntegerField(blank=True, null=True)),
                ("cdsr_page_no", models.IntegerField(blank=True, null=True)),
                ("cdsr_table_id", models.BigIntegerField(blank=True, null=True)),
                ("ddsr_no", models.IntegerField(blank=True, null=True)),
                ("ddsr_pg_no", models.IntegerField(blank=True, null=True)),
                ("ddsr_table_id", models.BigIntegerField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("cdsr_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "final_product_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("order_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("product_quantity", models.IntegerField(blank=True, null=True)),
                ("receipt_no", models.CharField(blank=True, max_length=255, null=True)),
                ("write_off_date", models.DateField(blank=True, max_length=255)),
                (
                    "write_off_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
