# Generated by Django 5.1.7 on 2025-03-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_register"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Register",
        ),
    ]
