from django.db import models

class CDSR(models.Model):
    cdsr_id = models.BigAutoField(primary_key=True)
    cdsr_no = models.IntegerField(null=True, blank=True)
    cdsr_pg_no = models.IntegerField(null=True, blank=True)
    active_product = models.IntegerField(null=True, blank=True)
    cdsr_name = models.CharField(max_length=255, null=True, blank=True)
    date_of_purchase = models.DateField(max_length=80, blank=True)
    product_category = models.CharField(max_length=80, null=True, blank=True)
    product_description = models.CharField(max_length=80, null=True, blank=True)
    product_quantity = models.IntegerField(null=True, blank=True)
    product_type = models.CharField(max_length=80, null=True, blank=True)
    purchase_authority = models.CharField(max_length=80, null=True, blank=True)
    purchase_year = models.CharField(max_length=40, null=True, blank=True)
    remaining_quantity = models.IntegerField(null=False)
    single_cost = models.BigIntegerField(null=True, blank=True)
    supplier = models.CharField(max_length=90, null=True, blank=True)
    total_cost = models.BigIntegerField(null=True, blank=True)
    writeoff_status = models.CharField(max_length=255, null=True, blank=True)

class DDSR(models.Model):
    ddsr_id = models.BigAutoField(primary_key=True)
    cdsr_name = models.CharField(max_length=255, null=True, blank=True)
    cdsr_no = models.IntegerField(null=True, blank=True)
    cdsr_page_no = models.IntegerField(null=True, blank=True)
    cdsr_table_id = models.BigIntegerField(null=True, blank=True)
    cost_unit = models.CharField(max_length=255, null=True, blank=True)
    date_of_receive = models.DateField(max_length=255, blank=True)
    ddsr_no = models.IntegerField(null=True, blank=True)
    ddsr_pg_no = models.IntegerField(null=True, blank=True)
    department = models.CharField(max_length=255, null=True, blank=True)
    product_category = models.CharField(max_length=255, null=True, blank=True)
    product_description = models.CharField(max_length=255, null=True, blank=True)
    product_quantity = models.IntegerField(null=True, blank=True)
    product_type = models.CharField(max_length=255, null=True, blank=True)
    accepted_product_quantity = models.IntegerField(null=True, blank=True)
    supplier_name = models.CharField(max_length=255, null=True, blank=True)
    total_cost = models.CharField(max_length=255, null=True, blank=True)
    writeoff_status = models.CharField(max_length=255, null=True, blank=True)
    year_of_buy = models.CharField(max_length=255, null=True, blank=True)
    

class ConsumeCDSR(models.Model):
    consume_cdsr_id = models.BigAutoField(primary_key=True)
    consume_cdsr_no = models.IntegerField(null=True, blank=True)
    consume_cdsr_page_no = models.IntegerField(null=True, blank=True)
    consume_cost_per_unit = models.BigIntegerField(null=True, blank=True)
    consume_date_of_purchase = models.DateField(max_length=255, blank=True)
    consume_order_no = models.IntegerField(null=True, blank=True)
    consume_cdsr_product_name = models.CharField(max_length=255, null=True, blank=True)
    consume_purchase_quantity = models.BigIntegerField(null=True, blank=True)
    consume_purchase_year = models.CharField(max_length=255, null=True, blank=True)
    consume_supplier_name = models.CharField(max_length=255, null=True, blank=True)
    consume_total = models.IntegerField(null=True, blank=True)
    final_product_quantity = models.BigIntegerField(null=True, blank=True)
    product_grant = models.CharField(max_length=255, null=True, blank=True)
    product_unit = models.CharField(max_length=255, null=True, blank=True)

class ConsumeDDSR(models.Model):
    consumeddsr_id = models.BigAutoField(primary_key=True)
    c_purchase_unit = models.CharField(max_length=255, null=True, blank=True)
    cdsr_no = models.IntegerField(null=True, blank=True)
    cdsr_pg_no = models.IntegerField(null=True, blank=True)
    consume_cdsr_id = models.BigIntegerField(null=True, blank=True)
    date_of_issue = models.DateField(max_length=255, blank=True)
    ddsr_total = models.FloatField(null=False)
    department = models.CharField(max_length=255, null=True, blank=True)
    final_product_quantity1 = models.BigIntegerField(null=True, blank=True)
    indent_no = models.BigIntegerField(null=True, blank=True)
    product_name = models.CharField(max_length=255, null=True, blank=True)
    ddsr_purchase_year = models.CharField(max_length=255, null=True, blank=True)
    quantity_issued = models.CharField(max_length=255, null=True, blank=True)
    supplier_name = models.CharField(max_length=255, null=True, blank=True)

class WriteOff(models.Model):
    writeoff_id = models.BigAutoField(primary_key=True)
    cdsr_no = models.IntegerField(null=True, blank=True)
    cdsr_page_no = models.IntegerField(null=True, blank=True)
    cdsr_table_id = models.BigIntegerField(null=True, blank=True)
    ddsr_no = models.IntegerField(null=True, blank=True)
    ddsr_pg_no = models.IntegerField(null=True, blank=True)
    ddsr_table_id = models.BigIntegerField(null=True, blank=True)
    department = models.CharField(max_length=255, null=True, blank=True)
    cdsr_name = models.CharField(max_length=255, null=True, blank=True)
    final_product_no = models.CharField(max_length=255, null=True, blank=True)
    product_name = models.CharField(max_length=255, null=True, blank=True)
    order_no = models.CharField(max_length=255, null=True, blank=True)
    product_category = models.CharField(max_length=255, null=True, blank=True)
    product_quantity = models.IntegerField(null=True, blank=True)
    receipt_no = models.CharField(max_length=255, null=True, blank=True)
    write_off_date = models.DateField(max_length=255, blank=True)
    write_off_year = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"WriteOff {self.writeoff_id}: {self.product_name}"
